model_provider = "openrouter"
model = "gpt-5"

# Unfortunately this is currently buggy due to API changes.
[model_providers.openrouter]
name = "openrouter"
base_url = "https://openrouter.ai/api/v1"
env_key = "OPENROUTER_API_KEY"
